@SegmentAtAPI_HostAddress = https://segmentat.onrender.com/api/v1
@youtubeUrl = "https://www.youtube.com/watch?v=keS8ZPaBZsI"

GET {{SegmentAtAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{SegmentAtAPI_HostAddress}}/fetch
Content-Type: application/json

{ 
    "youtubeUrl":{{youtubeUrl}}
}

###i7
POST {{SegmentAtAPI_HostAddress}}/download-segments
Content-Type: application/json

{
  "url": {{youtubeUrl}},
  "selectedQuality": "720p",
  "segments": [
    {
      "start": "00:00:00",
      "end": "00:03:00",
      "name": "Tom Holland video"
    }
  ],
  "outputDirectory": "C:\\Downloads\\segments"
}

